In [1]:
3+4

7

In [2]:
print(2 + 3)
print(2 - 3)
print(2 * 3)
print(10 / 2)
print(3 ** 2) # R 語言使用 3 ^ 2
print(10 % 4) # R 語言使用 10 %% 4

5
-1
6
5.0
9
2


In [ ]:
help(type)

In [4]:
print(type(5)) # 'int'
print(type(5.5)) # 'float'
print(type(5 + 3j)) # 'complex'
print(type(True)) # 'bool'
print(type(False)) # 'bool'
print(type("2017 ithome ironman")) # 'str'
#R中的變數類型有數值(numeric, integer, complex)、邏輯(logical-T/F)、文字(character)
#character 對應 str，然後 logical 對應 bool，以及 numeric 對應 float

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'bool'>
<class 'bool'>
<class 'str'>


In [5]:
days = 30
print("In order to become an ironman, you have to publish an article a day for " + days + " days in a row.")

TypeError: can only concatenate str (not "int") to str

In [6]:
print(1.0 == True) # True
print(0 == False) # True
print(1.2 + True) # 2.2
print(3 + True * 2) # 5
print("2017 ithome ironman" + " rocks!") # "2017 ithome ironman rocks!"
print("2017 ithome ironman " + "rocks" + "!" * 3) # "2017 ithome ironman rocks!!!"

True
True
2.2
5
2017 ithome ironman rocks!
2017 ithome ironman rocks!!!


In [ ]:
days = 30
days += 3 #days = days + 3
print(days)

In [1]:
import numpy as np
ironman = np.array([46,8,11,11,4,56]) #將list 用array的方式呈現出來
print(ironman)

[46  8 11 11  4 56]


In [2]:
print(type(ironman))

<class 'numpy.ndarray'>


In [4]:
articles = ironman * 30
print(articles)

[1380  240  330  330  120 1680]


In [10]:
import numpy as np
ironmen = np.array([46, 8, 11, 11, 4, 56])
print(ironmen[0]) # print第一組的資料

46


In [11]:
print(ironmen > 10) # print 哪幾組的人數超過10個人，會出現是T/F

[ True False  True  True False  True]


In [12]:
print(ironmen[ironmen > 10]) # print超過10個人的人數

[46 11 11 56]


In [15]:
import numpy as np
ironmen_2d_array = np.array([[46, 11, 4], [8, 11, 56]])
print(ironmen_2d_array[0, 0]) # print 第一組的人數
print(ironmen_2d_array > 10)
print(ironmen_2d_array[ironmen_2d_array > 10])

46
[[ True  True False]
 [False  True  True]]
[46 11 11 56]


In [16]:
# 用.size以及.shape來了解array的型態
import numpy as np
ironmen_2d_array = np.array([[46, 11, 4], [8, 11, 56]])
print(ironmen_2d_array.size) # 有幾個東西
print(ironmen_2d_array.shape) # 有點像是R裡面的dim

6
(2, 3)


In [20]:
# 開始data.frame的玩耍 -1
import pandas as pd
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [46, 8, 12, 12, 6, 58]
ironmen_dict = {"groups": groups,
                             "ironmen": ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
ironmen_df

groups  ironmen
0  Modern Web       46
1      DevOps        8
2       Cloud       12
3    Big Data       12
4    Security        6
5       自我挑戰組       58

In [21]:
# dataframe另外的寫法!! 驚人!!!
import pandas as pd
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [46, 8, 12, 12, 6, 58]
df = pd.DataFrame()
df["groups"] = groups
df["ironmen"] = ironmen
df

groups  ironmen
0  Modern Web       46
1      DevOps        8
2       Cloud       12
3    Big Data       12
4    Security        6
5       自我挑戰組       58

In [22]:
print(type(ironmen))

<class 'list'>


In [24]:
# 還有一種方式可以做dataFrame!!! 把array弄成dataframe
import numpy as np
import pandas as pd
my_2d_array = np.array([[1, 3], [2, 4]])
print(my_2d_array)
my_df = pd.DataFrame(my_2d_array, columns = ["col1", "col2"])
print(my_df)

[[1 3]
 [2 4]]
   col1  col2
0     1     3
1     2     4


In [44]:
 # 選擇元素或者欄位
import pandas as pd
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [46, 8, 12, 12, 6, 58]
ironmen_dict = {"groups": groups,
                "ironmen": ironmen}
ironmen_df = pd.DataFrame(ironmen_dict)
ironmen_df
print(ironmen_df.iloc[0:1, 1]) # 第一列第二欄：Modern Web 組的人數
print(ironmen_df.iloc[1, 1]) # compare with [0:1,1] ，只差在有沒有編號，如果是[0:2]就是列出兩個列
print("---")
print(ironmen_df.iloc[0:1,:]) # 第一列：Modern Web 組的組名與人數
print("---")
print(ironmen_df.iloc[:,1]) # 第二欄：各組的鐵人數
print("---")
print(ironmen_df["ironmen"]) # 各組的鐵人數
print("---")
print(ironmen_df.ironmen) # 各組的鐵人數

0    46
Name: ironmen, dtype: int64
---
       groups  ironmen
0  Modern Web       46
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: ironmen, dtype: int64
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: ironmen, dtype: int64
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: ironmen, dtype: int64


In [41]:
print(ironmen_df)
print(ironmen_df.iloc[2,0])

       groups  ironmen
0  Modern Web       46
1      DevOps        8
2       Cloud       12
3    Big Data       12
4    Security        6
5       自我挑戰組       58
Cloud


In [46]:
import pandas as pd

groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [46, 8, 12, 12, 6, 58]

ironmen_dict = {"groups": groups,
                "ironmen": ironmen
                }
ironmen_df = pd.DataFrame(ironmen_dict)
# ironmen_df.loc[:,"ironmen"] > 10 這個結果是T / F，然後把T的印出來
print(ironmen_df[ironmen_df.loc[:,"ironmen"] > 10]) 

       groups  ironmen
0  Modern Web       46
2       Cloud       12
3    Big Data       12
5       自我挑戰組       58


In [45]:
ironmen_df.loc[:,"ironmen"] > 10

0     True
1    False
2     True
3     True
4    False
5     True
Name: ironmen, dtype: bool

In [47]:
import pandas as pd

groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen = [46, 8, 12, 12, 6, 58]

ironmen_dict = {"groups": groups,
                "ironmen": ironmen
                }

print(ironmen_df.shape) # 回傳列數與欄數
print("---")
print(ironmen_df.describe()) # 回傳描述性統計
print("---")
print(ironmen_df.head(3)) # 回傳前三筆觀測值
print("---")
print(ironmen_df.tail(3)) # 回傳後三筆觀測值
print("---")
print(ironmen_df.columns) # 回傳欄位名稱
print("---")
print(ironmen_df.index) # 回傳 index


(6, 2)
---
         ironmen
count   6.000000
mean   23.666667
std    22.393451
min     6.000000
25%     9.000000
50%    12.000000
75%    37.500000
max    58.000000
---
       groups  ironmen
0  Modern Web       46
1      DevOps        8
2       Cloud       12
---
     groups  ironmen
3  Big Data       12
4  Security        6
5     自我挑戰組       58
---
Index(['groups', 'ironmen'], dtype='object')
---
RangeIndex(start=0, stop=6, step=1)
